# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'src/ErrorProne.NET.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  # Disable VSIX deployment for CI builds to improve performance
  DeployExtension: 'false'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: 4.6.1

- task: NuGetCommand@2
  inputs:
    feedsToUse: config
    nugetConfigPath: 'src/NuGet.config'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'src/**/*.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger:trx'
